catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
minimumReleaseAgeExclude:
  - "@vitejs/plugin-react@6.1.0"
  - framer-motion@13.1.1
  - motion-dom@13.1.1
  - motion@13.1.1
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
